/** Common country list for profile forms. Not exhaustive (ISO-3166 has ~250);
 * covers the countries most likely to sign up plus an explicit "Other" so
 * nobody is blocked from completing their profile. */
export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "New Zealand",
  "Ireland",
  "India",
  "Pakistan",
  "Bangladesh",
  "Philippines",
  "Nigeria",
  "South Africa",
  "Egypt",
  "Morocco",
  "Kenya",
  "Ghana",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Turkey",
  "Israel",
  "Germany",
  "France",
  "Spain",
  "Italy",
  "Portugal",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Ukraine",
  "Russia",
  "Greece",
  "Romania",
  "Czech Republic",
  "Hungary",
  "China",
  "Japan",
  "South Korea",
  "Taiwan",
  "Vietnam",
  "Thailand",
  "Indonesia",
  "Malaysia",
  "Singapore",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Venezuela",
  "Other",
] as const;

export type Country = (typeof COUNTRIES)[number];
