/** Language options shared by native/target/spoken/teaching language fields
 * across student and tutor profile forms. */
export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Dutch",
  "Russian",
  "Ukrainian",
  "Polish",
  "Turkish",
  "Arabic",
  "Hebrew",
  "Persian (Farsi)",
  "Hindi",
  "Urdu",
  "Bengali",
  "Punjabi",
  "Chinese (Mandarin)",
  "Cantonese",
  "Japanese",
  "Korean",
  "Vietnamese",
  "Thai",
  "Indonesian",
  "Malay",
  "Tagalog",
  "Swahili",
  "Amharic",
  "Greek",
  "Romanian",
  "Czech",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
] as const;

export type Language = (typeof LANGUAGES)[number];
